name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:     
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: |
          cd src
          tsc -t es2015 ms-store-badge.ts
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_WATER_0EAF5100F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "/dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
    deploy_misc:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: azure/login@v1
          with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Upload to Blob Storage
          uses: Azure/CLI@v1
          with:
            inlineScript: |
                az storage blob upload --account-name badgedelivery --account-key 2ngmcw/u/QDpUUTcMc71xuoCJ8MhCmq4OmV2+LL9MiAfwi+EMp1r9EPcDWALk8+J4U9CeGgTMvQnwSzvpesjfA== --container-name '$web' --file /dist/ms-store-badge.bundled.js --name 'ms-store-badge.bundled.js'
        - name: Purge CDN
          uses: Azure/CLI@v1
          with:
            inlineScript: |
                az cdn endpoint purge --content-paths "/*" --profile-name "getbadgecdn" --name "getbadgecdn.azureedge.net" --resource-group "rg-store-app-badge"




  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_WATER_0EAF5100F }}
          action: "close"
